// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA47oJ8DwBCldzeecHvRYC33g0oW-xcr8A',
    appId: '1:405212531300:web:b0e0382d54db4ec72d2d71',
    messagingSenderId: '405212531300',
    projectId: 'aivora-ai-44b35',
    authDomain: 'aivora-ai-44b35.firebaseapp.com',
    storageBucket: 'aivora-ai-44b35.firebasestorage.app',
    measurementId: 'G-XJXNNN5TVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSIltePeeADoX3U6yYctjeO_tfQ2tQwxg',
    appId: '1:405212531300:android:e2744370438626892d2d71',
    messagingSenderId: '405212531300',
    projectId: 'aivora-ai-44b35',
    storageBucket: 'aivora-ai-44b35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdDsaFC76fFtMBX7prvkjIe0iP5jbtwr0',
    appId: '1:405212531300:ios:83a632b80c701ebf2d2d71',
    messagingSenderId: '405212531300',
    projectId: 'aivora-ai-44b35',
    storageBucket: 'aivora-ai-44b35.firebasestorage.app',
    iosBundleId: 'com.aivora.aiVora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdDsaFC76fFtMBX7prvkjIe0iP5jbtwr0',
    appId: '1:405212531300:ios:83a632b80c701ebf2d2d71',
    messagingSenderId: '405212531300',
    projectId: 'aivora-ai-44b35',
    storageBucket: 'aivora-ai-44b35.firebasestorage.app',
    iosBundleId: 'com.aivora.aiVora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA47oJ8DwBCldzeecHvRYC33g0oW-xcr8A',
    appId: '1:405212531300:web:635144fa3f1108662d2d71',
    messagingSenderId: '405212531300',
    projectId: 'aivora-ai-44b35',
    authDomain: 'aivora-ai-44b35.firebaseapp.com',
    storageBucket: 'aivora-ai-44b35.firebasestorage.app',
    measurementId: 'G-K9ZFSZTZ1L',
  );
}
