import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../chat/chat_page.dart';
import '../tools/tools_page.dart';
import '../../core/theme/app_theme.dart';
import '../../services/history/chat_history_service.dart';

class HomePage extends StatefulWidget {
  final String? userName;

  const HomePage({
    super.key,
    this.userName,
  });

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  int _selectedIndex = 0;
  List<ChatHistoryItem> _historyItems = [];
  List<String> _folders = ['General'];
  bool _historyLoading = false;
  String _historySearch = '';
  String _selectedFolder = 'All';

  @override
  void initState() {
    super.initState();
    _loadHistory();
    _loadProfileData();
    _loadFolders();
  }

  Future<void> _loadProfileData() async {
    final prefs = await SharedPreferences.getInstance();
    final user = FirebaseAuth.instance.currentUser;
    if (!mounted) return;
    setState(() {
      _customName = prefs.getString("aivora_profile_name") ?? "";
      _customEmail = prefs.getString("aivora_profile_email") ?? user?.email ?? "";
    });
  }

  Future<void> _loadFolders() async {
    final folders = await ChatHistoryService.getFolders();
    if (!mounted) return;
    setState(() => _folders = folders);
  }

  Future<void> _loadHistory() async {
    setState(() => _historyLoading = true);
    final items = await ChatHistoryService.getHistory();
    if (!mounted) return;
    setState(() {
      _historyItems = items;
      _historyLoading = false;
    });
  }

  final List<_AivoraTool> _tools = const [
    _AivoraTool(
      icon: Icons.chat_bubble_rounded,
      name: 'AI Chat',
      subtitle: 'Ask anything',
      accentColor: AppTheme.cyan,
    ),
    _AivoraTool(
      icon: Icons.edit_note_rounded,
      name: 'AI Writer',
      subtitle: 'Create content',
      accentColor: AppTheme.primary,
    ),
    _AivoraTool(
      icon: Icons.auto_fix_high_rounded,
      name: 'Rewriter',
      subtitle: 'Improve text',
      accentColor: AppTheme.secondary,
    ),
    _AivoraTool(
      icon: Icons.summarize_rounded,
      name: 'Summarizer',
      subtitle: 'Shorten text',
      accentColor: AppTheme.cyan,
    ),
    _AivoraTool(
      icon: Icons.translate_rounded,
      name: 'Translator',
      subtitle: 'Translate text',
      accentColor: AppTheme.primary,
    ),
    _AivoraTool(
      icon: Icons.image_rounded,
      name: 'Text to Image',
      subtitle: 'Create images',
      accentColor: AppTheme.secondary,
    ),
    _AivoraTool(
      icon: Icons.video_library_rounded,
      name: 'Text to Video',
      subtitle: 'Create videos',
      accentColor: AppTheme.cyan,
    ),
    _AivoraTool(
      icon: Icons.mic_rounded,
      name: 'Text to Voice',
      subtitle: 'Generate voice',
      accentColor: AppTheme.primary,
    ),
    _AivoraTool(
      icon: Icons.picture_as_pdf_rounded,
      name: 'PDF Chat',
      subtitle: 'Talk to PDFs',
      accentColor: AppTheme.secondary,
    ),
    _AivoraTool(
      icon: Icons.description_rounded,
      name: 'Documents',
      subtitle: 'Create documents',
      accentColor: AppTheme.cyan,
    ),
    _AivoraTool(
      icon: Icons.badge_rounded,
      name: 'Resume Builder',
      subtitle: 'Build your CV',
      accentColor: AppTheme.primary,
    ),
    _AivoraTool(
      icon: Icons.music_note_rounded,
      name: 'AI Music',
      subtitle: 'Create music',
      accentColor: AppTheme.secondary,
    ),
  ];

  String _customName = '';
  String _customEmail = '';

  String get _displayName {
    final name = _customName.trim().isNotEmpty ? _customName.trim() : widget.userName?.trim();

    if (name == null || name.isEmpty) {
      return 'there';
    }

    return name;
  }

  String get _dailyTip {
    const tips = [
      "Use AI to save time, not to replace your thinking.",
      "Break a big task into small prompts for better AI results.",
      "Give AI clear context before asking for an answer.",
      "Always verify important information generated by AI.",
      "Save your best prompts so you can reuse them later.",
      "Ask AI to explain difficult topics in simple language.",
      "Small improvements every day can create big results.",
    ];
    return tips[DateTime.now().difference(DateTime(DateTime.now().year, 1, 1)).inDays % tips.length];
  }

  String get _greeting {
    final hour = DateTime.now().hour;

    if (hour < 12) {
      return 'Good Morning';
    }

    if (hour < 17) {
      return 'Good Afternoon';
    }

    if (hour < 21) {
      return 'Good Evening';
    }

    return 'Good Night';
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.background,
      body: SafeArea(
        child: IndexedStack(
          index: _selectedIndex,
          children: [
            _buildHome(),
            const ToolsPage(),
            _buildHistory(),
            _buildProfile(),
          ],
        ),
      ),
      bottomNavigationBar: _buildBottomNavigation(),
    );
  }

  Widget _buildHome() {
    return SingleChildScrollView(
      physics: const BouncingScrollPhysics(),
      padding: const EdgeInsets.fromLTRB(18, 18, 18, 30),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _buildTopHeader(),
          const SizedBox(height: 28),
          Text(
            '$_greeting, $_displayName 👋',
            style: const TextStyle(
              color: AppTheme.textPrimary,
              fontSize: 27,
              fontWeight: FontWeight.w800,
              letterSpacing: -0.5,
            ),
          ),
          const SizedBox(height: 7),
          const Text(
            'What would you like to create today?',
            style: TextStyle(
              color: AppTheme.textSecondary,
              fontSize: 14,
            ),
          ),
          const SizedBox(height: 22),
          _buildMainAiCard(),
        const SizedBox(height: 14),
        _buildDailyTipCard(),
          const SizedBox(height: 25),
          _buildSectionHeader(
            'Quick Actions',
            'View all',
            () {
              setState(() => _selectedIndex = 1);
            },
          ),
          const SizedBox(height: 13),
          Row(
            children: [
              Expanded(
                child: _buildQuickAction(
                  icon: Icons.chat_rounded,
                  title: 'New Chat',
                  subtitle: 'Ask AIVORA',
                  color: AppTheme.cyan,
                  onTap: _openChat,
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: _buildQuickAction(
                  icon: Icons.auto_awesome_rounded,
                  title: 'Create',
                  subtitle: 'Make something',
                  color: AppTheme.secondary,
                  onTap: () {
                    setState(() => _selectedIndex = 1);
                  },
                ),
              ),
            ],
          ),
          const SizedBox(height: 25),
          _buildSectionHeader(
            'AI Tools',
            'Explore',
            () {
              setState(() => _selectedIndex = 1);
            },
          ),
          const SizedBox(height: 13),
          GridView.builder(
            shrinkWrap: true,
            physics: const NeverScrollableScrollPhysics(),
            itemCount: 6,
            gridDelegate:
                const SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 2,
              crossAxisSpacing: 12,
              mainAxisSpacing: 12,
              childAspectRatio: 1.08,
            ),
            itemBuilder: (context, index) {
              return _buildToolCard(_tools[index]);
            },
          ),
          const SizedBox(height: 26),
          _buildSectionHeader(
            'Recent',
            'History',
            () {
              setState(() => _selectedIndex = 2);
            },
          ),
          const SizedBox(height: 13),
          _buildRecentCard(),
        ],
      ),
    );
  }

  Widget _buildTopHeader() {
    return Row(
      children: [
        Container(
          width: 48,
          height: 48,
          decoration: BoxDecoration(
            gradient: const LinearGradient(
              colors: [
                AppTheme.cyan,
                AppTheme.primary,
                AppTheme.secondary,
              ],
            ),
            borderRadius: BorderRadius.circular(15),
            boxShadow: [
              BoxShadow(
                color: AppTheme.primary.withValues(alpha: 0.28),
                blurRadius: 18,
              ),
            ],
          ),
          child: const Icon(
            Icons.auto_awesome_rounded,
            color: Colors.white,
            size: 26,
          ),
        ),
        const SizedBox(width: 12),
        const Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'AIVORA',
                style: TextStyle(
                  color: AppTheme.textPrimary,
                  fontSize: 20,
                  fontWeight: FontWeight.w900,
                  letterSpacing: 1.2,
                ),
              ),
              Text(
                'AI CREATIVE WORKSPACE',
                style: TextStyle(
                  color: AppTheme.textSecondary,
                  fontSize: 8,
                  fontWeight: FontWeight.w700,
                  letterSpacing: 1.3,
                ),
              ),
            ],
          ),
        ),
        Container(
          decoration: BoxDecoration(
            color: AppTheme.surface,
            borderRadius: BorderRadius.circular(14),
            border: Border.all(
              color: AppTheme.primary.withValues(alpha: 0.22),
            ),
          ),
          child: IconButton(
            onPressed: () {},
            icon: const Icon(
              Icons.workspace_premium_rounded,
              color: AppTheme.cyan,
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildDailyTipCard() { return Container(padding: const EdgeInsets.all(18), decoration: BoxDecoration(color: AppTheme.surface, borderRadius: BorderRadius.circular(22), border: Border.all(color: AppTheme.cyan.withValues(alpha: 0.22))), child: Row(children: [const Icon(Icons.lightbulb_rounded, color: AppTheme.cyan, size: 28), const SizedBox(width: 14), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('DAILY AI TIP', style: TextStyle(color: AppTheme.cyan, fontSize: 11, fontWeight: FontWeight.w800, letterSpacing: 1.4)), const SizedBox(height: 7), Text(_dailyTip, style: const TextStyle(color: AppTheme.textPrimary, fontSize: 14, height: 1.4, fontWeight: FontWeight.w600))]))])); }
  Widget _buildMainAiCard() {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        gradient: const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            Color(0xFF102C55),
            Color(0xFF08172F),
            Color(0xFF170D35),
          ],
        ),
        borderRadius: BorderRadius.circular(27),
        border: Border.all(
          color: AppTheme.cyan.withValues(alpha: 0.22),
        ),
        boxShadow: [
          BoxShadow(
            color: AppTheme.primary.withValues(alpha: 0.16),
            blurRadius: 38,
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                width: 52,
                height: 52,
                decoration: BoxDecoration(
                  shape: BoxShape.circle,
                  gradient: const LinearGradient(
                    colors: [
                      AppTheme.cyan,
                      AppTheme.primary,
                      AppTheme.secondary,
                    ],
                  ),
                  boxShadow: [
                    BoxShadow(
                      color: AppTheme.cyan.withValues(alpha: 0.28),
                      blurRadius: 20,
                    ),
                  ],
                ),
                child: const Icon(
                  Icons.auto_awesome_rounded,
                  color: Colors.white,
                  size: 27,
                ),
              ),
              const SizedBox(width: 13),
              const Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'AIVORA AI',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                  SizedBox(height: 2),
                  Text(
                    'Your intelligent workspace',
                    style: TextStyle(
                      color: AppTheme.textSecondary,
                      fontSize: 11,
                    ),
                  ),
                ],
              ),
            ],
          ),
          const SizedBox(height: 20),
          const Text(
            'Think. Create.\nGo beyond limits. ⚡',
            style: TextStyle(
              color: AppTheme.cyan,
              fontSize: 25,
              height: 1.12,
              fontWeight: FontWeight.w800,
            ),
          ),
          const SizedBox(height: 9),
          const Text(
            'Chat, write, create images, explore ideas and more with AIVORA.',
            style: TextStyle(
              color: Colors.white70,
              fontSize: 12.5,
              height: 1.4,
            ),
          ),
          const SizedBox(height: 19),
          SizedBox(
            width: double.infinity,
            height: 49,
            child: DecoratedBox(
              decoration: BoxDecoration(
                gradient: const LinearGradient(
                  colors: [
                    AppTheme.cyan,
                    AppTheme.primary,
                    AppTheme.secondary,
                  ],
                ),
                borderRadius: BorderRadius.circular(16),
              ),
              child: ElevatedButton.icon(
                onPressed: _openChat,
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.transparent,
                  shadowColor: Colors.transparent,
                  foregroundColor: Colors.white,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(16),
                  ),
                ),
                icon: const Icon(Icons.chat_rounded),
                label: const Text(
                  'Start AI Chat',
                  style: TextStyle(fontWeight: FontWeight.w800),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildQuickAction({
    required IconData icon,
    required String title,
    required String subtitle,
    required Color color,
    required VoidCallback onTap,
  }) {
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(22),
      child: Container(
        padding: const EdgeInsets.all(15),
        decoration: BoxDecoration(
          color: AppTheme.surface,
          borderRadius: BorderRadius.circular(22),
          border: Border.all(
            color: color.withValues(alpha: 0.32),
          ),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              width: 43,
              height: 43,
              decoration: BoxDecoration(
                color: color.withValues(alpha: 0.12),
                borderRadius: BorderRadius.circular(14),
              ),
              child: Icon(
                icon,
                color: color,
                size: 22,
              ),
            ),
            const SizedBox(height: 12),
            Text(
              title,
              style: const TextStyle(
                color: AppTheme.textPrimary,
                fontSize: 14,
                fontWeight: FontWeight.w800,
              ),
            ),
            const SizedBox(height: 3),
            Text(
              subtitle,
              style: const TextStyle(
                color: AppTheme.textSecondary,
                fontSize: 10.5,
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildToolCard(_AivoraTool tool) {
    return InkWell(
      onTap: () {
        if (tool.name == 'AI Chat') {
          _openChat();
          return;
        }

        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              '${tool.name} will be connected next.',
            ),
          ),
        );
      },
      borderRadius: BorderRadius.circular(22),
      child: Container(
        padding: const EdgeInsets.all(15),
        decoration: BoxDecoration(
          color: AppTheme.surface,
          borderRadius: BorderRadius.circular(22),
          border: Border.all(
            color: tool.accentColor.withValues(alpha: 0.28),
          ),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              width: 44,
              height: 44,
              decoration: BoxDecoration(
                color: tool.accentColor.withValues(alpha: 0.12),
                borderRadius: BorderRadius.circular(14),
              ),
              child: Icon(
                tool.icon,
                color: tool.accentColor,
                size: 23,
              ),
            ),
            const SizedBox(height: 11),
            Text(
              tool.name,
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
              style: const TextStyle(
                color: AppTheme.textPrimary,
                fontSize: 13,
                fontWeight: FontWeight.w700,
              ),
            ),
            const SizedBox(height: 3),
            Text(
              tool.subtitle,
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
              style: const TextStyle(
                color: AppTheme.textSecondary,
                fontSize: 10,
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildRecentCard() {
    if (_historyItems.isEmpty) {
      return Container(
        width: double.infinity,
        padding: const EdgeInsets.all(18),
        decoration: BoxDecoration(
          color: AppTheme.surface,
          borderRadius: BorderRadius.circular(22),
          border: Border.all(color: AppTheme.primary.withValues(alpha: 0.24)),
        ),
        child: const Row(
          children: [
            Icon(Icons.history_rounded, color: AppTheme.cyan, size: 30),
            SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text('Recent Activity', style: TextStyle(color: AppTheme.textPrimary, fontSize: 13, fontWeight: FontWeight.w700)),
                  SizedBox(height: 4),
                  Text('Start a conversation to see it here.', style: TextStyle(color: AppTheme.textSecondary, fontSize: 10.5)),
                ],
              ),
            ),
          ],
        ),
      );
    }

    final recent = _historyItems.take(3).toList();
    return Column(
      children: recent.map((item) => Container(
        margin: const EdgeInsets.only(bottom: 8),
        decoration: BoxDecoration(
          color: AppTheme.surface,
          borderRadius: BorderRadius.circular(18),
          border: Border.all(color: AppTheme.primary.withValues(alpha: 0.18)),
        ),
        child: ListTile(
          dense: true,
          leading: const CircleAvatar(
            backgroundColor: AppTheme.surface2,
            child: Icon(Icons.chat_bubble_outline_rounded, color: AppTheme.cyan, size: 20),
          ),
          title: Text(item.title, maxLines: 1, overflow: TextOverflow.ellipsis, style: const TextStyle(color: AppTheme.textPrimary, fontSize: 13, fontWeight: FontWeight.w700)),
          subtitle: Text(item.preview, maxLines: 1, overflow: TextOverflow.ellipsis, style: const TextStyle(color: AppTheme.textSecondary, fontSize: 11)),
          trailing: const Icon(Icons.chevron_right_rounded, color: AppTheme.cyan),
          onTap: () => _openChat(item.id),
        ),
      )).toList(),
    );
  }

  Widget _buildSectionHeader(
    String title,
    String action,
    VoidCallback onAction,
  ) {
    return Row(
      children: [
        Expanded(
          child: Text(
            title,
            style: const TextStyle(
              color: AppTheme.textPrimary,
              fontSize: 18,
              fontWeight: FontWeight.w800,
            ),
          ),
        ),
        TextButton(
          onPressed: onAction,
          child: Text(
            action,
            style: const TextStyle(
              color: AppTheme.cyan,
              fontWeight: FontWeight.w700,
            ),
          ),
        ),
      ],
    );
  }



  List<ChatHistoryItem> get _filteredHistory {
    final query = _historySearch.trim().toLowerCase();
    return _historyItems.where((item) {
      final folderMatch = _selectedFolder == 'All' || item.folder == _selectedFolder;
      final textMatch = query.isEmpty ||
          item.title.toLowerCase().contains(query) ||
          item.preview.toLowerCase().contains(query);
      return folderMatch && textMatch;
    }).toList();
  }

  Future<void> _createFolder() async {
    final controller = TextEditingController();

    final name = await showDialog<String>(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: AppTheme.surface,
        title: const Text(
          'Create Folder',
          style: TextStyle(color: AppTheme.textPrimary),
        ),
        content: TextField(
          controller: controller,
          autofocus: true,
          style: const TextStyle(color: AppTheme.textPrimary),
          decoration: const InputDecoration(
            hintText: 'Folder name',
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel'),
          ),
          FilledButton(
            onPressed: () => Navigator.pop(context, controller.text.trim()),
            child: const Text('Create'),
          ),
        ],
      ),
    );

    controller.dispose();

    if (name == null || name.trim().isEmpty) {
      return;
    }

    await ChatHistoryService.createFolder(name);

    if (!mounted) {
      return;
    }

    await _loadFolders();

    setState(() {
      _selectedFolder = name.trim();
    });
  }

  Future<void> _renameChat(ChatHistoryItem item) async {
    final controller = TextEditingController(text: item.title);

    final newTitle = await showDialog<String>(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: AppTheme.surface,
        title: const Text(
          'Rename Chat',
          style: TextStyle(color: AppTheme.textPrimary),
        ),
        content: TextField(
          controller: controller,
          autofocus: true,
          style: const TextStyle(color: AppTheme.textPrimary),
          decoration: const InputDecoration(
            hintText: 'Chat name',
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel'),
          ),
          FilledButton(
            onPressed: () => Navigator.pop(context, controller.text.trim()),
            child: const Text('Save'),
          ),
        ],
      ),
    );

    controller.dispose();

    if (newTitle == null || newTitle.trim().isEmpty) {
      return;
    }

    await ChatHistoryService.renameConversation(
      item.id,
      newTitle.trim(),
    );

    if (mounted) {
      await _loadHistory();
    }
  }

  Future<void> _moveChat(ChatHistoryItem item) async {
    final folders = await ChatHistoryService.getFolders();

    if (!mounted) {
      return;
    }

    final selected = await showDialog<String>(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: AppTheme.surface,
        title: const Text(
          'Move Chat',
          style: TextStyle(color: AppTheme.textPrimary),
        ),
        content: SizedBox(
          width: double.maxFinite,
          child: ListView(
            shrinkWrap: true,
            children: folders.map((folder) {
              return ListTile(
                leading: Icon(
                  folder == item.folder
                      ? Icons.radio_button_checked_rounded
                      : Icons.folder_outlined,
                  color: folder == item.folder
                      ? AppTheme.cyan
                      : AppTheme.textSecondary,
                ),
                title: Text(
                  folder,
                  style: const TextStyle(
                    color: AppTheme.textPrimary,
                  ),
                ),
                onTap: () => Navigator.pop(context, folder),
              );
            }).toList(),
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel'),
          ),
        ],
      ),
    );

    if (selected == null || selected == item.folder) {
      return;
    }

    await ChatHistoryService.moveConversation(
      item.id,
      selected,
    );

    if (mounted) {
      await _loadHistory();
    }
  }

  Future<void> _deleteChat(ChatHistoryItem item) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: AppTheme.surface,
        title: const Text(
          'Delete Chat?',
          style: TextStyle(color: AppTheme.textPrimary),
        ),
        content: Text(
          'Delete "${item.title}" permanently?',
          style: const TextStyle(
            color: AppTheme.textSecondary,
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text('Cancel'),
          ),
          FilledButton(
            onPressed: () => Navigator.pop(context, true),
            child: const Text('Delete'),
          ),
        ],
      ),
    );

    if (confirmed != true) {
      return;
    }

    await ChatHistoryService.deleteConversation(item.id);

    if (!mounted) {
      return;
    }

    await _loadHistory();

    if (!mounted) {
      return;
    }

    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Chat deleted'),
        duration: Duration(seconds: 1),
      ),
    );
  }

  Widget _buildHistory() {
    return ListView(
      padding: const EdgeInsets.fromLTRB(16, 18, 16, 24),
      children: [
        Row(
          children: [
            const Expanded(
              child: Text(
                "History",
                style: TextStyle(
                  color: AppTheme.textPrimary,
                  fontSize: 25,
                  fontWeight: FontWeight.w900,
                ),
              ),
            ),
            IconButton(
              onPressed: () async {
                final query = await showSearch<String>(
                  context: context,
                  delegate: _HistorySearchDelegate(_historyItems),
                );

                if (query != null && mounted) {
                  setState(() {
                    _historySearch = query;
                  });
                }
              },
              icon: const Icon(
                Icons.search_rounded,
                color: AppTheme.cyan,
              ),
            ),
          ],
        ),

        const SizedBox(height: 14),

        SizedBox(
          height: 42,
          child: ListView(
            scrollDirection: Axis.horizontal,
            children: [
              ChoiceChip(
                label: const Text('All'),
                selected: _selectedFolder == 'All',
                onSelected: (_) {
                  setState(() {
                    _selectedFolder = 'All';
                  });
                },
                selectedColor: AppTheme.primary.withValues(alpha: 0.30),
                backgroundColor: AppTheme.surface,
                labelStyle: TextStyle(
                  color: _selectedFolder == 'All'
                      ? AppTheme.cyan
                      : AppTheme.textSecondary,
                  fontWeight: FontWeight.w700,
                ),
                side: BorderSide(
                  color: AppTheme.cyan.withValues(alpha: 0.20),
                ),
              ),

              const SizedBox(width: 8),

              ..._folders.map(
                (folder) => Padding(
                  padding: const EdgeInsets.only(right: 8),
                  child: ChoiceChip(
                    avatar: const Icon(
                      Icons.folder_outlined,
                      size: 16,
                    ),
                    label: Text(folder),
                    selected: _selectedFolder == folder,
                    onSelected: (_) {
                      setState(() {
                        _selectedFolder = folder;
                      });
                    },
                    selectedColor:
                        AppTheme.primary.withValues(alpha: 0.30),
                    backgroundColor: AppTheme.surface,
                    labelStyle: TextStyle(
                      color: _selectedFolder == folder
                          ? AppTheme.cyan
                          : AppTheme.textSecondary,
                      fontWeight: FontWeight.w700,
                    ),
                    side: BorderSide(
                      color: AppTheme.primary.withValues(alpha: 0.20),
                    ),
                  ),
                ),
              ),

              ActionChip(
                avatar: const Icon(
                  Icons.add_rounded,
                  size: 18,
                ),
                label: const Text('Folder'),
                onPressed: _createFolder,
                backgroundColor: AppTheme.surface,
                labelStyle: const TextStyle(
                  color: AppTheme.cyan,
                  fontWeight: FontWeight.w700,
                ),
                side: BorderSide(
                  color: AppTheme.cyan.withValues(alpha: 0.22),
                ),
              ),
            ],
          ),
        ),

        const SizedBox(height: 18),

        Container(
          padding: const EdgeInsets.all(20),
          decoration: BoxDecoration(
            gradient: const LinearGradient(
              colors: [
                AppTheme.surface2,
                AppTheme.surface,
              ],
            ),
            borderRadius: BorderRadius.circular(24),
            border: Border.all(
              color: AppTheme.cyan.withValues(alpha: 0.18),
            ),
          ),
          child: const Row(
            children: [
              Icon(
                Icons.history_rounded,
                color: AppTheme.cyan,
                size: 30,
              ),
              SizedBox(width: 14),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      "Recent Activity",
                      style: TextStyle(
                        color: AppTheme.textPrimary,
                        fontSize: 17,
                        fontWeight: FontWeight.w800,
                      ),
                    ),
                    SizedBox(height: 4),
                    Text(
                      "Your AI conversations and creations will appear here.",
                      style: TextStyle(
                        color: AppTheme.textSecondary,
                        fontSize: 12,
                        height: 1.4,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),

        const SizedBox(height: 24),

        Row(
          children: [
            const Expanded(
              child: Text(
                "RECENT",
                style: TextStyle(
                  color: AppTheme.textSecondary,
                  fontSize: 11,
                  fontWeight: FontWeight.w800,
                  letterSpacing: 1.4,
                ),
              ),
            ),
            if (_selectedFolder != 'All')
              Text(
                _selectedFolder,
                style: const TextStyle(
                  color: AppTheme.cyan,
                  fontSize: 11,
                  fontWeight: FontWeight.w700,
                ),
              ),
          ],
        ),

        const SizedBox(height: 12),

        if (_historyLoading)
          const Center(
            child: Padding(
              padding: EdgeInsets.all(32),
              child: CircularProgressIndicator(
                color: AppTheme.cyan,
              ),
            ),
          )
        else if (_filteredHistory.isEmpty)
          Container(
            padding: const EdgeInsets.symmetric(
              vertical: 38,
              horizontal: 24,
            ),
            decoration: BoxDecoration(
              color: AppTheme.surface,
              borderRadius: BorderRadius.circular(22),
              border: Border.all(
                color: AppTheme.primary.withValues(alpha: 0.16),
              ),
            ),
            child: const Column(
              children: [
                Icon(
                  Icons.auto_awesome_rounded,
                  color: AppTheme.cyan,
                  size: 42,
                ),
                SizedBox(height: 14),
                Text(
                  'No conversations found',
                  style: TextStyle(
                    color: AppTheme.textPrimary,
                    fontSize: 16,
                    fontWeight: FontWeight.w800,
                  ),
                ),
                SizedBox(height: 7),
                Text(
                  'Start a conversation or choose another folder.',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: AppTheme.textSecondary,
                    fontSize: 12,
                    height: 1.5,
                  ),
                ),
              ],
            ),
          )
        else
          ..._filteredHistory.map(
            (item) => Container(
              margin: const EdgeInsets.only(bottom: 10),
              decoration: BoxDecoration(
                color: AppTheme.surface,
                borderRadius: BorderRadius.circular(18),
                border: Border.all(
                  color: AppTheme.primary.withValues(alpha: 0.16),
                ),
              ),
              child: ListTile(
                onTap: () => _openChat(item.id),
                leading: const CircleAvatar(
                  backgroundColor: AppTheme.surface2,
                  child: Icon(
                    Icons.chat_bubble_outline_rounded,
                    color: AppTheme.cyan,
                  ),
                ),
                title: Text(
                  item.title,
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                  style: const TextStyle(
                    color: AppTheme.textPrimary,
                    fontSize: 14,
                    fontWeight: FontWeight.w700,
                  ),
                ),
                subtitle: Text(
                  item.preview,
                  maxLines: 2,
                  overflow: TextOverflow.ellipsis,
                  style: const TextStyle(
                    color: AppTheme.textSecondary,
                    fontSize: 12,
                  ),
                ),
                trailing: PopupMenuButton<String>(
                  icon: const Icon(
                    Icons.more_vert_rounded,
                    color: AppTheme.textSecondary,
                  ),
                  onSelected: (value) {
                    if (value == 'rename') {
                      _renameChat(item);
                    } else if (value == 'move') {
                      _moveChat(item);
                    } else if (value == 'delete') {
                      _deleteChat(item);
                    }
                  },
                  itemBuilder: (context) => const [
                    PopupMenuItem(
                      value: 'rename',
                      child: ListTile(
                        leading: Icon(Icons.edit_rounded),
                        title: Text('Rename'),
                      ),
                    ),
                    PopupMenuItem(
                      value: 'move',
                      child: ListTile(
                        leading: Icon(Icons.drive_file_move_rounded),
                        title: Text('Move to folder'),
                      ),
                    ),
                    PopupMenuItem(
                      value: 'delete',
                      child: ListTile(
                        leading: Icon(Icons.delete_outline_rounded),
                        title: Text('Delete'),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
      ],
    );
  }

  Future<void> _editProfile() async {
    final user = FirebaseAuth.instance.currentUser;
    final nameController = TextEditingController(text: _customName);
    final emailController = TextEditingController(text: _customEmail.isNotEmpty ? _customEmail : (user?.email ?? ''));

    final save = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: AppTheme.surface,
        title: const Text('Edit Profile', style: TextStyle(color: AppTheme.textPrimary)),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextField(
              controller: nameController,
              style: const TextStyle(color: AppTheme.textPrimary),
              decoration: const InputDecoration(labelText: 'Name'),
            ),
            const SizedBox(height: 14),
            TextField(
              controller: emailController,
              keyboardType: TextInputType.emailAddress,
              style: const TextStyle(color: AppTheme.textPrimary),
              decoration: const InputDecoration(labelText: 'Email'),
            ),
          ],
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context, false), child: const Text('Cancel')),
          FilledButton(onPressed: () => Navigator.pop(context, true), child: const Text('Save')),
        ],
      ),
    );

    if (save != true) {
      nameController.dispose();
      emailController.dispose();
      return;
    }

    final newName = nameController.text.trim();
    final newEmail = emailController.text.trim();
    nameController.dispose();
    emailController.dispose();

    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('aivora_profile_name', newName);
    await prefs.setString('aivora_profile_email', newEmail);

    if (!mounted) return;
    setState(() {
      _customName = newName;
      _customEmail = newEmail;
    });

    if (user != null && newEmail.isNotEmpty && newEmail != user.email) {
      try {
        await user.verifyBeforeUpdateEmail(newEmail);
        if (!mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Verification email sent to the new email.')),
        );
      } catch (e) {
        if (!mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Email update failed: ')),
        );
      }
    }
  }

  Future<void> _logout() async {
    await FirebaseAuth.instance.signOut();
  }

  Widget _buildProfile() {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(30),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              width: 88,
              height: 88,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                gradient: const LinearGradient(
                  colors: [
                    AppTheme.cyan,
                    AppTheme.primary,
                    AppTheme.secondary,
                  ],
                ),
              ),
              child: const Icon(
                Icons.person_rounded,
                size: 43,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 18),
            Text(
              _displayName == 'there'
                  ? 'AIVORA User'
                  : _displayName,
              style: const TextStyle(
                color: AppTheme.textPrimary,
                fontSize: 25,
                fontWeight: FontWeight.w800,
              ),
            ),
            const SizedBox(height: 7),
            const Text(
              'Create. Chat. Imagine.',
              style: TextStyle(
                color: AppTheme.textSecondary,
              ),
            ),
            const SizedBox(height: 24),
            Row(mainAxisAlignment: MainAxisAlignment.center,children:[OutlinedButton.icon(onPressed: _editProfile,style: OutlinedButton.styleFrom(foregroundColor: AppTheme.cyan,side: BorderSide(color: AppTheme.cyan.withValues(alpha: 0.35))),icon: const Icon(Icons.edit_rounded),label: const Text('Edit Profile')),const SizedBox(width: 12),OutlinedButton.icon(onPressed: _logout,style: OutlinedButton.styleFrom(foregroundColor: Colors.redAccent,side: BorderSide(color: Colors.redAccent.withValues(alpha: 0.35))),icon: const Icon(Icons.logout_rounded),label: const Text('Logout'))]),
          ],
        ),
      ),
    );
  }

  Widget _buildBottomNavigation() {
    return NavigationBar(
      backgroundColor: AppTheme.surface,
      indicatorColor: AppTheme.primary.withValues(alpha: 0.18),
      selectedIndex: _selectedIndex,
      onDestinationSelected: (index) {
        setState(() => _selectedIndex = index);
      },
      destinations: const [
        NavigationDestination(
          icon: Icon(Icons.home_outlined),
          selectedIcon: Icon(Icons.home_rounded),
          label: 'Home',
        ),
        NavigationDestination(
          icon: Icon(Icons.grid_view_outlined),
          selectedIcon: Icon(Icons.grid_view_rounded),
          label: 'Tools',
        ),
        NavigationDestination(
          icon: Icon(Icons.history_outlined),
          selectedIcon: Icon(Icons.history_rounded),
          label: 'History',
        ),
        NavigationDestination(
          icon: Icon(Icons.person_outline_rounded),
          selectedIcon: Icon(Icons.person_rounded),
          label: 'Profile',
        ),
      ],
    );
  }

  Future<void> _openChat([String? chatId]) async {
    await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => ChatPage(chatId: chatId),
      ),
    );
    if (mounted) {
      await _loadHistory();
    }
  }
}

class _AivoraTool {
  final IconData icon;
  final String name;
  final String subtitle;
  final Color accentColor;

  const _AivoraTool({
    required this.icon,
    required this.name,
    required this.subtitle,
    this.accentColor = AppTheme.primary,
  });
}

class _HistorySearchDelegate extends SearchDelegate<String> {
  final List<ChatHistoryItem> items;

  _HistorySearchDelegate(this.items);

  @override
  List<Widget>? buildActions(BuildContext context) {
    return [
      if (query.isNotEmpty)
        IconButton(
          icon: const Icon(Icons.clear),
          onPressed: () => query = '',
        ),
    ];
  }

  @override
  Widget? buildLeading(BuildContext context) {
    return IconButton(
      icon: const Icon(Icons.arrow_back),
      onPressed: () => close(context, ''),
    );
  }

  @override
  Widget buildResults(BuildContext context) {
    return _buildList();
  }

  @override
  Widget buildSuggestions(BuildContext context) {
    return _buildList();
  }

  Widget _buildList() {
    final q = query.trim().toLowerCase();

    final results = items.where((item) {
      return q.isEmpty ||
          item.title.toLowerCase().contains(q) ||
          item.preview.toLowerCase().contains(q);
    }).toList();

    if (results.isEmpty) {
      return const Center(
        child: Text(
          'No matching conversations',
          style: TextStyle(color: AppTheme.textSecondary),
        ),
      );
    }

    return ListView.builder(
      padding: const EdgeInsets.all(16),
      itemCount: results.length,
      itemBuilder: (context, index) {
        final item = results[index];

        return ListTile(
          leading: const Icon(
            Icons.chat_bubble_outline_rounded,
            color: AppTheme.cyan,
          ),
          title: Text(
            item.title,
            style: const TextStyle(color: AppTheme.textPrimary),
          ),
          subtitle: Text(
            item.preview,
            maxLines: 2,
            overflow: TextOverflow.ellipsis,
            style: const TextStyle(color: AppTheme.textSecondary),
          ),
          onTap: () => close(context, item.title),
        );
      },
    );
  }
}
