name: Build AIVORA AI APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.5'
          channel: stable
          cache: true

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze Flutter project
        run: flutter analyze

      - name: Build APK
        env:
          APP_CHECK_DEBUG_TOKEN: ${{ secrets.APP_CHECK_DEBUG_TOKEN }}
        run: flutter build apk --release --dart-define=APP_CHECK_DEBUG_TOKEN="$APP_CHECK_DEBUG_TOKEN"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AIVORA-AI-APK
          path: build/app/outputs/flutter-apk/app-release.apk
